
defaults: &defaults
  adapter: postgresql


development:
  <<: *defaults
  database: fred4321_development

test:
  <<: *defaults
  database: fred4321_test


production:
  <<: *defaults
  database: fred4321_production
